### ISSUE TITLE
Cannot run tuneflow on local machine

### ISSUE THREAD

**Issue by jaideep2** [tuneflow/tuneflow-devkit-py#4]
Hello,
Is there a way to run tuneflow UI locally on windows machine from source? I know I can use TuneFlow Desktop, but where is the source code? Could not find in documentation.
Thanks

**Comment by andantei** [comment]
Hi  Jaideep, we are upgrading the way plugins are loaded and triggered so the current version is temporarily outdated, we are releasing the new version of TuneFlow Desktop soon, so stay tuned!

About running the UI from source: we are gradually open sourcing more repositories but as of now there is no plan for the UI yet.
